# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Screenshot/Screenshot.csproj'

- task: XamarinAndroid@1
  inputs:
    projectFile: 'sample/Sample.Android/Sample.Android.csproj'
    outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
    configuration: 'Release'
    clean: true
    msbuildVersionOption: 'latest'
    msbuildArchitectureOption: 'x64'
    jdkOption: 'JDKVersion'

- task: XamariniOS@2
  inputs:
    solutionFile: 'sample/Sample.iOS/Sample.iOS.csproj'
    configuration: 'Release'
    clean: true
    packageApp: true
    runNugetRestore: false



- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'sample/Sample/Sample.csproj'